version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/JourneyIntoTheBackend
hooks:
  BeforeInstall:
    - location: scripts/npm-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: root
      timeout: 300
  ApplicationStop:
    - location: scripts/npm-stop.sh
      runas: root
      timeout: 300